### ISSUE TITLE
Add on not being loaded

### ISSUE THREAD

**Issue by Skipslegdays** [Relintai/Relintais-Enemy-Kooldown-Tracker-WotLK#3]
I cannot find the checkbox to enable/disable this add on. Do I need to rename it to something after dragging it into the folder?

**Comment by Relintai** [comment]
The folder has to be named `Rekt` like in the release zip-s. https://github.com/Relintai/Relintais-Enemy-Kooldown-Tracker-WotLK/releases/tag/1.11.1

**Comment by Skipslegdays** [comment]
It works now. Tyvm.
I noticed that stun DR is tracked for my paladin's HoJ, but not warlock's Shadowfury. Is there some setting I need to turn on or debug?

**Comment by Relintai** [comment]
Apparently 2 ranks of shadowfury is missing from libdrdata.

**Comment by Relintai** [comment]
Please try https://github.com/Relintai/Relintais-Enemy-Kooldown-Tracker-WotLK/releases/tag/1.11.2 it should work now.

**Comment by Skipslegdays** [comment]
I appreciate the quick response! Say I want to customize the add on to remove Lay on Hands from CD Tracking. And to remove Silence from Interrupt Bar Tracking. Do I edit these lines of spells.lua?

![image](https://user-images.githubusercontent.com/64817317/122651231-78ffbe00-d105-11eb-88a3-594969a74f2d.png)
![image](https://user-images.githubusercontent.com/64817317/122651261-a8162f80-d105-11eb-9219-12fba7d0c980.png)

I also noticed felhunter spell lock is not tracked as a silence DR even though it is entered in the DRData.lua. Is there something else to be added?

![image](https://user-images.githubusercontent.com/64817317/122651457-ef50f000-d106-11eb-80e0-a8b6a0663d81.png)

**Comment by Relintai** [comment]
"Say I want to customize the add on to remove Lay on Hands from CD Tracking."

Just remove the lines that you screenshotted.

"And to remove Silence from Interrupt Bar Tracking."

Change the last `true` to `false`, like:

```[15487] = {45, nil, 45, 45, 45, 5, "Priest", "silence", false, false, false}, --Silence```

"I also noticed felhunter spell lock is not tracked as a silence DR even though it is entered in the DRData.lua. Is there something else to be added?" 

I noticed that rank 1 spell lock was missing from spells.lua, so I added that. With a little luck that will fix the issue, if not, I'm not sure what's the problem with it. If I manage to find my wrath client I'll try to look at it.

**Comment by Skipslegdays** [comment]
I tried what you suggested and it worked. I love how customizable the add on is. It's like having Afflicted + Interruptbar + quick and easy configs.

I did notice a visual bug where each time I log a new char, this shows up. If I disable and enable the add on, it goes away. Any idea what could be causing it?
![image](https://user-images.githubusercontent.com/64817317/123009256-5cc08300-d38a-11eb-89a8-6e094343ff29.png)

**Comment by Relintai** [comment]
It shouldn't be like that, I'll look into it a bit later.

**Comment by Relintai** [comment]
I couldn't replicate it, but it should be fixed now. So please let me know if it's still bugged out.

**Comment by Skipslegdays** [comment]
It is still happening. Any recommendation on how I can debug this? Unchecking and rechecking "Enabled" makes it go away, so a quick and dirty fix might be to make the add on do that when logging in.

**Comment by Relintai** [comment]
Oops I think it should actually work now, please try the new release.

I think what's happening is that this addon used to set a 50 second cooldown to the cooldown frames after they get created (which happens on login and on /reload), and then I hide their parent frame, and one of the addon that you use that add numbers to the cooldown frames don't like this. I have OmniCC installed, and that particular version has no problem with this, so I never caught it.

Also the fact that they all have the blink icon points to this as I create the frames with that particular icon.

As for debugging, if it still happens try to disable omnicc like addons to see if it goes away, if it does send me that addon, so I can mess around with it until I find a way to make it work.

**Comment by Skipslegdays** [comment]
I tried the latest version and the countdown numbers no longer show up, but the blink icons are still there. Even when all other add ons are disabled. Here's the OmniCC version I am using, although I don't think that's what's causing the icons anymore.

[OmniCC.zip](https://github.com/Relintai/Relintais-Enemy-Kooldown-Tracker-WotLK/files/6720469/OmniCC.zip)

**Comment by Relintai** [comment]
"tried the latest version and the countdown numbers no longer show up, but the blink icons are still there. "

Okay, at least that tells me that I'm messing with the right piece of code.

I added a new release, please try that too, based on this I'm hoping that this might fix the issue for good.

"Even when all other add ons are disabled. Here's the OmniCC version I am using, although I don't think that's what's causing the icons anymore."

Yeah, if it still happens while all addons are disabled then what I said is definitely not the issue.

Anyway I tried your OmniCC version just in case, but I still can't replicate this, so it's just going to take a bit more trial and error.

**Comment by Skipslegdays** [comment]
It worked! Thank you so much
